services:
  database:
    image: postgres:14
    container_name: medods_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medods

volumes:
  postgres_data:
    driver: local

networks:
  medods:
    driver: bridge